added git tags and check if commit was already run

diff --git a/.github/workflows/step-2-dbt-to-dremio.yaml b/.github/workflows/step-2-dbt-to-dremio.yaml
--- a/.github/workflows/step-2-dbt-to-dremio.yaml
+++ b/.github/workflows/step-2-dbt-to-dremio.yaml
@@ -26,6 +26,13 @@ jobs:
         run: |
           OPEN_PR_COUNT=$(gh pr list --state open --json number -q '. | length')
           if [ $OPEN_PR_COUNT -gt 0 ]; then echo "::error::ERROR: There are $OPEN_PR_COUNT open pull requests. Please merge them before rerunning this pipeline." && exit 1; fi;
+      - name: Check if latest commit was already run
+        run: |
+          git fetch --prune --unshallow --tags   # Make sure the that tags are being fetched
+          LATEST_TAG=$(git describe --tags --exact-match)
+          if git describe --tags --exact-match > /dev/null 2>&1; then
+            echo "::error::WARNING: Latest commit was already run (Tag: $LATEST_TAG). No new changes to deploy." && exit 1
+          fi
       - name: Set up Python
         uses: actions/setup-python@v3
         with:
@@ -37,3 +44,10 @@ jobs:
       - name: Run dbt
         run: |
           dbt --log-format-file json run --profiles-dir dbt_profile --select $DBT_MODEL_DIR --target prod
+      - name: Create git tag
+        if: success()
+        run: |
+          TS=$(date +"%Y-%m-%d_%H-%M-%S")
+          GIT_TAG=RUN-ON-$TS
+          git tag $GIT_TAG
+          git push origin $GIT_TAG
